# Dataset reader arguments
dataset:
  img_norm: 1
  concat_history: true
  max_sequence_length: 20
  vocab_min_count: 5

# Model related arguments
model:
  encoder: 'attn'
  decoder: 'gen'

  img_feature_size: 2048
  word_embedding_size: 300
  lstm_hidden_size: 512
  lstm_num_layers: 2
  dropout: 0.2
  is_bilstm: true
  num_attns: 2

# Optimization related arguments
solver:
  batch_size: 8 # 32 x num_gpus is a good rule of thumb
  num_epochs: 10
  initial_lr: 1e-3         # overfit: should changed to 1e-3 rather than 1e-2
  training_splits: "train"  # "trainval"
