# Dataset reader arguments
dataset:
  image_features_train_h5: '/home/ubuntu/datasets/myvisdial/data/features_faster_rcnn_x101_train.h5'
  image_features_val_h5: '/home/ubuntu/datasets/myvisdial/data/features_faster_rcnn_x101_val.h5'
  image_features_test_h5: '/home/ubuntu/datasets/myvisdial/data/features_faster_rcnn_x101_test.h5'
  word_counts_json: '/home/ubuntu/datasets/myvisdial/data/visdial_1.0_word_counts_train.json'

  img_norm: 1
  concat_history: true
  max_sequence_length: 20
  vocab_min_count: 5


# Model related arguments
model:
  encoder: 'lf'
  decoder: 'disc'

  img_feature_size: 2048
  word_embedding_size: 300
  lstm_hidden_size: 512
  lstm_num_layers: 2
  dropout: 0.5


# Optimization related arguments
solver:
  batch_size: 30 # 32 x num_gpus is a good rule of thumb
  num_epochs: 15
  initial_lr: 1e-3         # overfit: should changed to 1e-3 rather than 1e-2
  training_splits: "train"  # "trainval"
