# Dataset reader arguments
dataset:
  img_norm: 1
  concat_history: true
  max_sequence_length: 20
  vocab_min_count: 5

# Model related arguments
model:
  encoder: 'lf'
  decoder: 'gen'

  img_feature_size: 2048
  word_embedding_size: 300
  lstm_hidden_size: 512
  lstm_num_layers: 2
  dropout: 0.2


# Optimization related arguments
solver:
  training_splits: "train"  # "trainval"

