callbacks:
    log_dir: /home/quang/workspace/log/tensorboard/overfit/v001_abc_LP_lkf_Dlegacy
    online: false
    path_pretrained_ckpt: null
    resume: false
    save_dir: /media/local_workspace/quang/checkpoints/visdial/CVPR/overfit/v001_abc_LP_lkf_Dlegacy
    validate: true
config_name: overfit/v001_abc_LP_lkf_Dlegacy
dataset:
    concat_hist: false
    finetune: false
    glove_path: /media/local_workspace/quang/datasets/visdial/glove/embedding_Glove_840_300d.pkl
    is_add_boundaries: true
    is_legacy: false
    is_return_options: true
    max_seq_len: 20
    num_boxes: fixed
    overfit: false
    train_feat_img_path: /media/local_workspace/quang/datasets/visdial/legacy/features_faster_rcnn_x101_val.h5
    train_json_dialog_path: /media/local_workspace/quang/datasets/visdial/annotations/visdial_1.0_val.json
    train_json_word_count_path: /media/local_workspace/quang/datasets/visdial/annotations/visdial_1.0_word_counts_train.json
    val_feat_img_path: /media/local_workspace/quang/datasets/visdial/legacy/features_faster_rcnn_x101_val.h5
    val_json_dense_dialog_path: /media/local_workspace/quang/datasets/visdial/annotations/visdial_1.0_val_dense_annotations.json
    val_json_dialog_path: /media/local_workspace/quang/datasets/visdial/annotations/visdial_1.0_val.json
    vocab_min_count: 5
help: null
model:
    ca_has_layer_norm: true
    ca_has_proj_linear: false
    ca_has_residual: false
    ca_has_shared_attns: true
    ca_has_updated_hist: false
    ca_memory_size: 2
    ca_num_cross_attn_heads: 4
    ca_num_cross_attns: 1
    decoder_type: misc
    dropout: 0.1
    hidden_size: 512
    img_feat_size: 2048
    img_has_attributes: false
    img_has_bboxes: false
    img_has_classes: false
    img_num_attns: null
    test_mode: false
    txt_bidirectional: true
    txt_embedding_size: 300
    txt_has_decoder_layer_norm: true
    txt_has_layer_norm: true
    txt_has_pos_embedding: true
    txt_tokenizer: nlp
    txt_vocab_size: 11322
optional arguments:
    config_name: overfit/v001_abc_LP_lkf_Dlegacy
    help: null
    seed: 0
positional arguments: {}
seed: 0
solver:
    adam_betas:
    - 0.9
    - 0.997
    adam_eps: 1.0e-09
    batch_size: 24
    batch_size_multiplier: 1
    clip_norm: null
    cpu_workers: 8
    fp16: false
    init_lr: 0.005
    kd_alpha: null
    kd_temperature: null
    linear_gama: null
    ls_epsilon: 0.0
    milestone_steps: null
    min_lr: 1.0e-05
    num_epochs: 50
    num_samples: 2064
    optimizer: adam
    scheduler_type: CosineLR
    warmup_epochs: 1
    warmup_factor: 0.2
    weight_decay: 1.0e-05
