#!/usr/bin/env sh
CUDA_VISIBLE_DEVICES=0,1,2 /home/administrator/quang/anaconda3/bin/python /home/administrator/quang/workspace/repos/visdial/train.py \
--config_name train_simple/s09_simple_branch \
--decoder_type misc \
--init_lr 0.001 \
--scheduler_type "LinearLR" \
--batch_size 12 \
--num_epochs 12 \
--num_samples 123287 \
--ls_epsilon 0.0 \
--dropout 0.1 \
--img_has_bboxes \
--img_has_classes \
--img_has_attributes \
--ca_has_layer_norm \
--ca_has_shared_attns \
--ca_num_cross_attns 1 \
--txt_has_layer_norm \
--txt_has_decoder_layer_norm \
--txt_has_pos_embedding \
--val_feat_img_path "/media/local_workspace/quang/datasets/visdial/bottom-up-attention/val2018_resnet101_faster_rcnn_genome__num_boxes_50_50.h5" \
--train_feat_img_path "/media/local_workspace/quang/datasets/visdial/bottom-up-attention/trainval_resnet101_faster_rcnn_genome__num_boxes_50_50.h5"