callbacks:
    log_dir: /home/quang/checkpoints/s45/tensorboard
    online: false
    path_pretrained_ckpt: null
    resume: false
    save_dir: /home/quang/checkpoints/s45
    validate: true
config_name: s45
dataset:
    concat_hist: false
    finetune: false
    glove_path: /home/quang/datasets/glove/embedding_Glove_840_300d.pkl
    is_add_boundaries: true
    is_legacy: false
    is_return_options: true
    max_seq_len: 20
    num_boxes: fixed
    overfit: false
    train_feat_img_path: ~/datasets/bottom-up-attention/trainval_resnet101_faster_rcnn_genome__num_boxes_100_100.h5
    train_json_dialog_path: /home/quang/datasets/annotations/visdial_0.9_train.json
    train_json_word_count_path: /home/quang/datasets/annotations/visdial_1.0_word_counts_train.json
    val_feat_img_path: ~/datasets/bottom-up-attention/trainval_resnet101_faster_rcnn_genome__num_boxes_100_100.h5
    val_json_dense_dialog_path: null
    val_json_dialog_path: /home/quang/datasets/annotations/visdial_0.9_val.json
    vocab_min_count: 5
help: null
model:
    ca_every_head_attn: false
    ca_has_intra_attns: true
    ca_has_layer_norm: true
    ca_has_proj_linear: false
    ca_has_residual: true
    ca_has_shared_attns: true
    ca_has_updated_hist: true
    ca_memory_size: 2
    ca_num_cross_attn_heads: 4
    ca_num_cross_attns: 2
    decoder_type: misc
    dropout: 0.1
    encoder_out:
    - img
    - ques
    - hist
    hidden_size: 512
    img_feat_size: 2048
    img_has_attributes: false
    img_has_bboxes: true
    img_has_classes: false
    img_num_attns: null
    pred_heads: 1
    pred_sigmoid: false
    test_mode: false
    txt_bidirectional: true
    txt_embedding_size: 300
    txt_has_decoder_layer_norm: true
    txt_has_layer_norm: true
    txt_has_pos_embedding: true
    txt_tokenizer: nlp
    txt_vocab_size: 11322
no_comet: false
optional arguments:
    config_name: s45
    help: null
    no_comet: false
    seed: 0
positional arguments: {}
seed: 0
solver:
    adam_betas:
    - 0.9
    - 0.997
    adam_eps: 1.0e-09
    batch_size: 8
    batch_size_multiplier: 1
    clip_norm: null
    cpu_workers: 8
    fp16: false
    init_lr: 0.001
    kd_alpha: null
    kd_temperature: null
    linear_gama: 0.5
    ls_epsilon: 0.0
    milestone_steps:
    - 3
    - 5
    - 7
    - 9
    - 11
    - 13
    min_lr: 1.0e-05
    num_epochs: 15
    num_samples: 123287
    optimizer: adam
    scheduler_type: LinearLR
    warmup_epochs: 1
    warmup_factor: 0.2
    weight_decay: 1.0e-05
